- name: Kubeadm master
  hosts: master
  become: true

  tasks:

   - name: Set hostname
     ansible.builtin.shell: sudo hostnamectl set-hostname kubeadm-master
   
   - name: Create kubeadm cluster
     ansible.builtin.shell: | 
       kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version=1.32.0
     args:
      creates: /etc/kubernetes/admin.conf

   - name: Create kube directory
     file:
        path: /home/ansible/.kube
        owner: ansible
        group: ansible
        mode: 755
        recurse: yes

   - name: Copy config file
     ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ansible/.kube/config
      mode: '0744'
      remote_src: yes

   - name: Untaint control plane node
     ansible.builtin.shell: |
       kubectl --kubeconfig=/home/ansible/.kube/config taint nodes --all node-role.kubernetes.io/control-plane- 

   - name: Install calico
     ansible.builtin.shell: |
      kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/tigera-operator.yaml &&
                             kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/custom-resources.yaml

   - name: Print join command
     ansible.builtin.shell: |
      kubeadm token create --print-join-command > /tmp/join.txt

   - name: Fetch file
     ansible.builtin.fetch:
      src: /tmp/join.txt
      dest: /tmp/join.txt
      flat: true
