- name: Kubeadm node
  hosts: node
  become: true

  tasks:

   - name: Set hostname
     ansible.builtin.shell: sudo hostnamectl set-hostname kubeadm-node

   - name: Copy the join file to kubeadm node
     ansible.builtin.copy:
       src: /tmp/join.txt
       dest: /tmp/join.txt
       mode: 755
       register: result

   - name: Join the cluster
     ansible.builtin.shell: "{{result}}"