- name: Kubeadm node
  hosts: node
  become: true

  tasks:

   - name: Set hostname
     ansible.builtin.shell: sudo hostnamectl set-hostname kubeadm-node

   - name: Check if node has already joined the cluster
     ansible.builtin.stat:
      path: /etc/kubernetes/kubelet.conf
     register: kubelet_conf

   - name: Copy the join file to kubeadm node
     ansible.builtin.copy:
      src: /tmp/join.sh
      dest: /tmp/join.sh
      mode: "0755"

   - name: Adjust conntrack
     ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-conntrack.conf
      net.netfilter.nf_conntrack_max = 262144
      net.netfilter.nf_conntrack_buckets = 65536
      EOF
      sysctl --system

   - name: Join the cluster
     ansible.builtin.shell: /bin/bash /tmp/join.sh
     when: not kubelet_conf.stat.exists
