- name: Kubeadm master
  hosts: master
  become: true

  tasks:

    - name: Wait for node to be Ready
      ansible.builtin.command:
        cmd: >
          kubectl wait --kubeconfig=/home/ansible/.kube/config --for=condition=Ready node/kubeadm-node --timeout=300s
