- name: Deployment
  hosts: master
  become: true

  tasks:

    - name: Render Deployment
      ansible.builtin.template:
        src: templates/deployment.yaml.j2
        dest: /tmp/deployment.yaml

    - name: Show rendered deployment
      ansible.builtin.shell: cat /tmp/deployment.yaml
      register: deployment_yaml

    - debug:
        var: deployment_yaml.stdout_lines

    - name: Apply Deployment
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/deployment.yaml

    - name: Copy service manifest
      ansible.builtin.copy:
        src: templates/service.yaml
        dest: /tmp/service.yaml
        mode: "0644"

    - name: Expose Deployment
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/service.yaml

    - name: Get TargetGroupBinding
      kubernetes.core.k8s_info:
        kubeconfig: /home/ansible/.kube/config
        kind: TargetGroupBinding
        namespace: default
      register: tgb
      delegate_to: localhost

    - name: Extract ALB SG
      set_fact:
        alb_sg: >-
          {{ tgb.resources[0].spec.networking.ingress[0].from[0].securityGroup.groupID }}

    - name: Save ALB SG
      copy:
        dest: /tmp/alb_sg.txt
        content: "{{ alb_sg }}"