- name: Kubeadm master
  hosts: master
  become: true

  tasks:

   - name: Copy ingress manifest
     ansible.builtin.copy:
      src: templates/ingress.yaml
      dest: /tmp/ingress.yaml
      mode: "0644"

   - name: Apply ingress
     ansible.builtin.shell: kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/ingress.yaml

   - name: Wait for ALB and target group to be provisioned
     ansible.builtin.pause:
      seconds: 240
