- name: Kubeadm master
  hosts: master
  become: true

  tasks:

   - name: Copy ingress manifest
     ansible.builtin.copy:
      src: templates/ingress.yaml
      dest: /tmp/ingress.yaml
      mode: "0644"

   - name: Apply ingress
     ansible.builtin.shell: kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/ingress.yaml

   - name: Wait for TargetGroupBinding to exist
     ansible.builtin.command:
      cmd: >
        kubectl
        --kubeconfig=/home/ansible/.kube/config
        get targetgroupbinding
        -n default
        -o jsonpath={.items[0].metadata.name}
      register: tgb
      changed_when: false
      failed_when: false
      until: tgb.stdout | trim | length > 0
      retries: 30
      delay: 10

   - name: Get ALB security group
     ansible.builtin.command:
      cmd: >
        kubectl
        --kubeconfig=/home/ansible/.kube/config
        get targetgroupbinding
        -n default
        -o jsonpath={.items[0].spec.networking.ingress[0].from[0].securityGroup.groupID}
     register: alb_sg
     changed_when: false

   - name: Save ALB security group ID
     ansible.builtin.copy:
      dest: /tmp/alb_sg.txt
      content: "{{ alb_sg.stdout }}"
      mode: "0644"

   - name: Get Target Group ARN
     ansible.builtin.command:
      cmd: >
        kubectl
        --kubeconfig=/home/ansible/.kube/config
        get targetgroupbinding
        -n default
        -o jsonpath={.items[0].spec.targetGroupARN}
     register: tg_arn
     changed_when: false

   - name: Wait for healthy targets
     ansible.builtin.command:
      cmd: >
        aws elbv2 describe-target-health
        --target-group-arn {{ tg_arn.stdout }}
        --output json
     register: tg_health
     changed_when: false
     failed_when: false
     until: >
      (
        (tg_health.stdout | default('{}')) | from_json
      ).TargetHealthDescriptions
      | default([])
      | selectattr('TargetHealth.State', 'equalto', 'healthy')
      | list
      | length > 0
     retries: 30
     delay: 10

   - name: Output readiness
     ansible.builtin.debug:
      msg: "ALB READY - TG healthy"
