- name: ECR
  hosts: master
  become: true

  tasks:

   - name: Render ECR secret
     ansible.builtin.template:
      src: templates/ecr-secret.yaml.j2
      dest: /tmp/ecr-secret.yaml

   - name: Apply ECR secret
     ansible.builtin.shell: |
       kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/ecr-secret.yaml

   - name: Render service account
     ansible.builtin.template:
      src: templates/serviceaccount.yaml
      dest: /tmp/serviceaccount.yaml

   - name: Apply service account
     ansible.builtin.shell: |
      kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/serviceaccount.yaml
