- name: Secret  
  hosts: master
  become: true

  tasks:

    - name: Render RDS secret
      ansible.builtin.template:
        src: templates/rds-secret.yaml.j2
        dest: /tmp/secret.yaml

    - name: Apply RDS secret
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/ansible/.kube/config apply -f /tmp/secret.yaml
