- name: Secret
  hosts: master
  become: true

  tasks:

    - name: Create RDS secret
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/ansible/.kube/config \
        create secret generic rds-secret \
        --from-literal=db-user=postgres \
        --from-literal=db-password="{{ db_pass }}" \
        --from-literal=db-host="{{ db_host }}" \
        --from-literal=db-name=k8s \
        --dry-run=client -o yaml | \
        kubectl --kubeconfig=/home/ansible/.kube/config apply -f -
