- name: K8s
  hosts: master
  become: true

  tasks:

   - name: Create secret
     ansible.builtin.shell: |
      cat <<EOF | kubectl --kubeconfig=/home/ansible/.kube/config apply -f -
      apiVersion: v1
      data:
        db-user=postgres
        db-password= {{ db_pass }}
        db-host= {{ db_host }}
        db-name=k8s
      kind: Secret
      metadata:
        name: rds-secret
      EOF
